avr = ../../avr

programmer = dragon_isp
device = atmega328p
frequency = 20000000

main = main

offset = 0x7000

lfuse = 0xF7:m
hfuse = 0xD8:m
efuse = 0xFC:m
lock = 0xEF:m

include $(avr)/build/Makefile
